
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.6.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
Prisma.prismaVersion = {
  client: "7.6.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.ServerScalarFieldEnum = {
  id: 'id',
  name: 'name',
  username: 'username',
  type: 'type',
  provider: 'provider',
  moreDetails: 'moreDetails',
  publicIp: 'publicIp',
  privateIp: 'privateIp',
  privateKey: 'privateKey',
  publicKey: 'publicKey',
  proxyHandler: 'proxyHandler',
  loadBalancer: 'loadBalancer',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ServerLogScalarFieldEnum = {
  id: 'id',
  serverId: 'serverId',
  command: 'command',
  commandName: 'commandName',
  output: 'output',
  status: 'status',
  runAt: 'runAt',
  source: 'source',
  accountId: 'accountId'
};

exports.Prisma.SavedCommandScalarFieldEnum = {
  id: 'id',
  name: 'name',
  command: 'command',
  description: 'description',
  nextCommands: 'nextCommands',
  variables: 'variables',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ApplicationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  appIcon: 'appIcon',
  location: 'location',
  language: 'language',
  repository: 'repository',
  networkAccess: 'networkAccess',
  commands: 'commands',
  information: 'information',
  owner: 'owner',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  environments: 'environments',
  files: 'files'
};

exports.Prisma.ApplicationServerMapScalarFieldEnum = {
  id: 'id',
  serverId: 'serverId',
  applicationId: 'applicationId',
  status: 'status',
  isPrimary: 'isPrimary'
};

exports.Prisma.DomainScalarFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status',
  addedAt: 'addedAt',
  verificationCode: 'verificationCode',
  verified: 'verified'
};

exports.Prisma.EnvironmentVariableScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  targetType: 'targetType',
  selectedTargets: 'selectedTargets',
  isConfidential: 'isConfidential',
  protectValue: 'protectValue',
  createdAt: 'createdAt'
};

exports.Prisma.AppErrorScalarFieldEnum = {
  id: 'id',
  message: 'message',
  level: 'level',
  source: 'source',
  timestamp: 'timestamp',
  stack: 'stack'
};

exports.Prisma.ProjectScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdOn: 'createdOn'
};

exports.Prisma.LoggerActivityScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  type: 'type',
  data: 'data',
  loggedOn: 'loggedOn'
};

exports.Prisma.LiveSessionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  cwd: 'cwd',
  status: 'status',
  history: 'history',
  serverLogId: 'serverLogId',
  serverId: 'serverId'
};

exports.Prisma.AccessTokenScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  name: 'name',
  key: 'key'
};

exports.Prisma.IntelligenceModelScalarFieldEnum = {
  id: 'id',
  title: 'title',
  provider: 'provider',
  model: 'model',
  description: 'description',
  currency: 'currency',
  inputPrice: 'inputPrice',
  outputPrice: 'outputPrice'
};

exports.Prisma.IntelligenceAccessScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  keyHash: 'keyHash',
  type: 'type',
  availableTo: 'availableTo',
  details: 'details',
  maxTokens: 'maxTokens',
  tokenBalance: 'tokenBalance',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.IntelligenceLogScalarFieldEnum = {
  id: 'id',
  accessId: 'accessId',
  details: 'details',
  from: 'from',
  type: 'type',
  balance: 'balance',
  devDetails: 'devDetails',
  loggedOn: 'loggedOn'
};

exports.Prisma.OpenFlowUsageLogScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  tokenLast4: 'tokenLast4',
  modelUsed: 'modelUsed',
  provider: 'provider',
  usedAt: 'usedAt'
};

exports.Prisma.PipelineScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  title: 'title',
  description: 'description',
  flowJson: 'flowJson'
};

exports.Prisma.PipelineLogScalarFieldEnum = {
  id: 'id',
  pipelineId: 'pipelineId',
  timestamp: 'timestamp',
  logBy: 'logBy',
  details: 'details'
};

exports.Prisma.DatabaseScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  connectionType: 'connectionType',
  connectionStatus: 'connectionStatus',
  credentails: 'credentails',
  authConfig: 'authConfig',
  lastValidatedAt: 'lastValidatedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  displayName: 'displayName',
  displayImage: 'displayImage',
  neupid: 'neupid'
};

exports.Prisma.PermitScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  portfolioId: 'portfolioId',
  assetType: 'assetType',
  assetId: 'assetId',
  role: 'role'
};

exports.Prisma.AuthzRoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  scope: 'scope'
};

exports.Prisma.AuthzCapabilityScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  scope: 'scope'
};

exports.Prisma.AuthzRoleCapabilityScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  capabilityId: 'capabilityId',
  scope: 'scope',
  denormalizedCapability: 'denormalizedCapability',
  roleName: 'roleName'
};

exports.Prisma.AuthzAccountAccessGrantScalarFieldEnum = {
  id: 'id',
  ownerAccountId: 'ownerAccountId',
  targetAccountId: 'targetAccountId',
  roleId: 'roleId',
  portfolioId: 'portfolioId'
};

exports.Prisma.AuthzAssetsAccessGrantScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  accountId: 'accountId',
  roleId: 'roleId',
  portfolioId: 'portfolioId',
  assetType: 'assetType'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.ApplicationServerMapStatus = exports.$Enums.ApplicationServerMapStatus = {
  stopped: 'stopped',
  started: 'started',
  inactive: 'inactive'
};

exports.Prisma.ModelName = {
  Server: 'Server',
  ServerLog: 'ServerLog',
  SavedCommand: 'SavedCommand',
  Application: 'Application',
  ApplicationServerMap: 'ApplicationServerMap',
  Domain: 'Domain',
  EnvironmentVariable: 'EnvironmentVariable',
  AppError: 'AppError',
  Project: 'Project',
  LoggerActivity: 'LoggerActivity',
  LiveSession: 'LiveSession',
  AccessToken: 'AccessToken',
  IntelligenceModel: 'IntelligenceModel',
  IntelligenceAccess: 'IntelligenceAccess',
  IntelligenceLog: 'IntelligenceLog',
  OpenFlowUsageLog: 'OpenFlowUsageLog',
  Pipeline: 'Pipeline',
  PipelineLog: 'PipelineLog',
  Database: 'Database',
  Account: 'Account',
  Permit: 'Permit',
  AuthzRole: 'AuthzRole',
  AuthzCapability: 'AuthzCapability',
  AuthzRoleCapability: 'AuthzRoleCapability',
  AuthzAccountAccessGrant: 'AuthzAccountAccessGrant',
  AuthzAssetsAccessGrant: 'AuthzAssetsAccessGrant'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
